### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rafay99-epic** [GrieferAtWork/wintouchg#1]
# Question 1:  
Is theses Guestres for Linux operating System or Window Operating System. ?

# Question 2:
If it is for Windows then can you explain the installing Method on windows.

# Question 3:
Please Expalin the working of the Application.

**Comment by GrieferAtWork** [comment]
# Answer 1:  
It's for windows (microsoft/NT) only (sorry), and there are no plans to port it to linux

# Answer 2:
That's already explained in-depth in the [main readme](https://github.com/GrieferAtWork/wintouchg#buildinstall). Automating this part is rather complicated since MS decided to put the `RegisterPointerInputTarget` function behind a locked door requiring certificates and a special install location.

# Answer 3:
If you mean the technical side, that's also explained in the main readme under [Inner Workings](https://github.com/GrieferAtWork/wintouchg#Inner_Workings).
If the question is about how to use the program itself, that's also described in there in detail, but if you want the TLDR: have you ever used multi-touch gestures on an old iPad? ... Well: wintouchg is pretty much just like those: Always using 4/5 fingers, you pinch to minimize, zoom to maximize, swipe left+right to switch between apps (here: windows from Alt+Tab), and can pull down to get a widget-panel with a bunch of toggles/sliders for stuff like wifi, bluetooth, brightness+sound, etc...
The only missing feature I never really got around to implement is an app switcher that's supposed to show up when you swipe up (similar to the overview you get when you press Win+Tab on Windows 10). Maybe one day I'll get around to implementing that one, too...

-----

Hope that answers all of your questions
